### ISSUE TITLE
Segfaults on Linux

### ISSUE THREAD

**Issue by duganchen** [libretro/beetle-psx-libretro#17]
Segfaults on Linux as soon as I try to launch a game. Here's the backtrace:

    Starting program: /usr/bin/retroarch -L /usr/lib64/libretro/mednafen_psx_libretro.so /storage/Downloads/Software/psx/R-Type\ Delta\ NTSC\ USA\ PSX.cue
    warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff7ffa000
    warning: Could not load shared library symbols for linux-vdso.so.1.
    Do you need "set solib-search-path" or "set sysroot"?
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    Didn't read whole file: /sys/devices/system/cpu/present.
    Didn't read whole file: /sys/devices/system/cpu/possible.
    [New Thread 0x7fffebea2700 (LWP 4848)]
    [New Thread 0x7fffeb6a1700 (LWP 4849)]

    Program received signal SIGSEGV, Segmentation fault.
    0x00007fffea74e722 in FrontIO::SaveMemcard(unsigned int) () from /usr/lib64/libretro/mednafen_psx_libretro.so
    (gdb) bt
    #0  0x00007fffea74e722 in FrontIO::SaveMemcard(unsigned int) () from /usr/lib64/libretro/mednafen_psx_libretro.so
    #1  0x00007fffeaa16e44 in CloseGame() () from /usr/lib64/libretro/mednafen_psx_libretro.so
    #2  0x00007fffeaa1b9e9 in retro_unload_game () from /usr/lib64/libretro/mednafen_psx_libretro.so
    #3  0x0000000000416b27 in event_deinit_core (reinit=true) at command_event.c:549
    #4  0x000000000041857a in event_command (cmd=EVENT_CMD_CORE_DEINIT) at command_event.c:1420
    #5  0x0000000000413e35 in rarch_main_init (argc=4, argv=0x7fffffffc7f8) at retroarch.c:1230
    #6  0x00000000004105b6 in main_load_content (argc=4, argv=0x7fffffffc7f8, args=0x0,
    environ_get=0x40f952 <frontend_linux_get_env>, process_args=0x0) at frontend/frontend.c:226 
    #7  0x0000000000410730 in rarch_main (argc=4, argv=0x7fffffffc7f8, data=0x0) at frontend/frontend.c:289
    #8  0x00000000004108bb in main (argc=4, argv=0x7fffffffc7f8) at frontend/frontend.c:343
    (gdb) quit

**Comment by duganchen** [comment]
Turns out that the fix was to rename the cue and bin files so that they did not have spaces, and to edit the cue file to point to the renamed bin file.
