### ISSUE TITLE
[Vulkan] Switching Widescreen Fix off/on crashes RetroArch since one of the most recent builds

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#210]
Reproducible with the following environment:

RetroArch version: RetroArch-2017-07-22-x64
Platform: Windows x64
Core Version:  https://github.com/libretro/beetle-psx-libretro/commit/399af92cefdddfb278132d5880a9d94203125c83
RetroArch Driver: Vulkan
Render: Vulkan
Graphics Card: GTX 970

A few builds ago and prior, switching the Widescreen Fix on/off was possible while playing a game. Now when doing so, RetroArch will instead crash. As a workaround, you can set a game to widescreen, and then without closing the GUI, hit Restart Content in the Quick Menu. This will allow switching to Widescreen.

**Comment by rz5** [comment]
@saftle I just tried to reproduce it on x86_64, Win10, trying both an Intel HD 520 and an AMD R5 M330.
Booted up Tekken 3 and the core option just worked.

I'll fetch the latest RA build and retry. Meanwhile, logs and stack traces are welcome

**Comment by rz5** [comment]
@saftle 
I can not reproduce it, and I only tested the GL driver/renderer
Widescreen hack works as intended.

RA version: 2017-07-29_RetroArch from the buildbot
Core version: 399af92
OS: Win10 (on both test systems)
GPU: Intel HD 520, AMD R5 M330, Nvidia GTX 970

**Comment by orbea** [comment]
@saftle Can you git bisect the issue and get a backtrace?

**Comment by saftle** [comment]
Oh my mistake. I copied my specs from a different issue. I had only tested it on Vulkan, but can safely say that the issue is new, since I luckily tried a build just a few days ago.

@orbea I sadly don't know how to compile a build, but can definitely learn if it's not reproducible with Vulkan on your guys' end. I should probably learn anyways eventually, since I test all of these nifty features :)

**Comment by orbea** [comment]
I don't know how to use windows, so someone else will have to help you learn. Or you can use a search engine and teach yourself. It should not be that hard.

**Comment by bparker06** [comment]
@saftle We have build instructions here:

http://buildbot.libretro.com/docs/compilation/windows/

**Comment by rz5** [comment]
With the Vulkan driver + Vulkan renderer, I do get a crash on boot.

Full backtrace:

```
(gdb) bt full
#0  0x00007ffffdb026e7 in igc64!getJITVersion ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\ki121392.inf_amd64_3c470e1034169038\igc64.dll
No symbol table info available.
#1  0x00007ffffdafa3bf in igc64!getJITVersion ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\ki121392.inf_amd64_3c470e1034169038\igc64.dll
No symbol table info available.
#2  0x00007ffffdaf4e6a in igc64!getJITVersion ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\ki121392.inf_amd64_3c470e1034169038\igc64.dll
No symbol table info available.
#3  0x00007ffffde2b648 in igc64!OpenCompiler12 ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\ki121392.inf_amd64_3c470e1034169038\igc64.dll
No symbol table info available.
#4  0x00007ffffde6d2a9 in igc64!OpenCompiler12 ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\ki121392.inf_amd64_3c470e1034169038\igc64.dll
No symbol table info available.
#5  0x00007fffbd0b1719 in vkDisplayModeControlINTEL ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\ki121392.inf_amd64_3c470e1034169038\igvk64.dll
No symbol table info available.
#6  0x00007fffbd0a0d21 in vkDisplayModeControlINTEL ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\ki121392.inf_amd64_3c470e1034169038\igvk64.dll
No symbol table info available.
#7  0x00007fffbd091fd0 in vkDisplayModeControlINTEL ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\ki121392.inf_amd64_3c470e1034169038\igvk64.dll
No symbol table info available.
#8  0x00007fffbd0d3ca3 in vkDisplayModeControlINTEL ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\ki121392.inf_amd64_3c470e1034169038\igvk64.dll
No symbol table info available.
#9  0x0000000015d03b4b in Vulkan::Device::bake_program (this=0x11757f60,
    program=...) at parallel-psx/vulkan/device.cpp:151
        shader = @0x75a9450: {<IntrusivePtrEnabled<Vulkan::Shader>> = {
            reference_count = 2}, device = 0xa829540,
          stage = Vulkan::ShaderStage::Compute, module = 0xddeb608, layout = {
            attribute_mask = 0, push_constant_offset = 0,
            push_constant_range = 8, sets = {{sampled_image_mask = 2,
                storage_image_mask = 1, uniform_buffer_mask = 0,
                storage_buffer_mask = 0, sampled_buffer_mask = 0,
                input_attachment_mask = 0, stages = 32}, {
                sampled_image_mask = 0, storage_image_mask = 0,
                uniform_buffer_mask = 1, storage_buffer_mask = 0,
                sampled_buffer_mask = 0, input_attachment_mask = 0,
                stages = 32}, {sampled_image_mask = 0,
                storage_image_mask = 0, uniform_buffer_mask = 0,
                storage_buffer_mask = 0, sampled_buffer_mask = 0,
                input_attachment_mask = 0, stages = 0}, {
                sampled_image_mask = 0, storage_image_mask = 0,
                uniform_buffer_mask = 0, storage_buffer_mask = 0,
                sampled_buffer_mask = 0, input_attachment_mask = 0,
                stages = 0}}}}
        info = {sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
          pNext = 0x0, flags = 0, stage = {
            sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            pNext = 0x0, flags = 0, stage = VK_SHADER_STAGE_COMPUTE_BIT,
            module = 0xddeb608,
            pName = 0x15eea7ac <_ZN6VulkanL27VULKAN_DESCRIPTOR_RING_SIZEE+4> "main", pSpecializationInfo = 0x0}, layout = 0xae8ba08,
          basePipelineHandle = 0x0, basePipelineIndex = 0}
        compute_pipeline = 0x75a9578
        layout = {attribute_mask = 0, sets = {{sampled_image_mask = 2,
              storage_image_mask = 1, uniform_buffer_mask = 0,
              storage_buffer_mask = 0, sampled_buffer_mask = 0,
              input_attachment_mask = 0, stages = 32}, {
              sampled_image_mask = 0, storage_image_mask = 0,
              uniform_buffer_mask = 1, storage_buffer_mask = 0,
              sampled_buffer_mask = 0, input_attachment_mask = 0,
              stages = 32}, {sampled_image_mask = 0, storage_image_mask = 0,
              uniform_buffer_mask = 0, storage_buffer_mask = 0,
              sampled_buffer_mask = 0, input_attachment_mask = 0,
              stages = 0}, {sampled_image_mask = 0, storage_image_mask = 0,
              uniform_buffer_mask = 0, storage_buffer_mask = 0,
              sampled_buffer_mask = 0, input_attachment_mask = 0,
              stages = 0}}, ranges = {{stageFlags = 0, offset = 0, size = 0},
            {stageFlags = 0, offset = 0, size = 0}, {stageFlags = 0,
              offset = 0, size = 0}, {stageFlags = 0, offset = 0, size = 0}, {
              stageFlags = 0, offset = 0, size = 0}, {stageFlags = 32,
              offset = 0, size = 8}}, num_ranges = 0,
          descriptor_set_mask = 3,
          push_constant_layout_hash = 8609674887807254021}
        h = {h = 8609674887807254021}
#10 0x0000000015d02fd5 in Vulkan::Device::create_program (this=0x11757f60,
    compute_data=0x15ebed60 <PSX::resolve_to_unscaled_2>, compute_size=4884)
    at parallel-psx/vulkan/device.cpp:50
        compute = {data = 0x75a9450}
        program = {data = 0x75a9520}
#11 0x0000000015cf73d3 in PSX::Renderer::init_pipelines (this=0x7596ac0)
    at parallel-psx/renderer/renderer.cpp:136
No locals.
#12 0x0000000015cf6bb1 in PSX::Renderer::Renderer (this=0x7596ac0,
    device=..., scaling=1, state=0x0) at parallel-psx/renderer/renderer.cpp:72
        info = {domain = Vulkan::ImageDomain::Transient, width = 1024,
          height = 512, depth = 1, levels = 1, format = VK_FORMAT_D32_SFLOAT,
          type = VK_IMAGE_TYPE_2D, layers = 1, usage = 32,
          samples = VK_SAMPLE_COUNT_1_BIT, flags = 0, misc = 0,
          initial_layout = VK_IMAGE_LAYOUT_UNDEFINED}
        dither_info = {domain = (unknown: 292931584), width = 0, height = 37,
          depth = 0, levels = 1, format = VK_FORMAT_UNDEFINED,
          type = VK_IMAGE_TYPE_2D, layers = 0, usage = 3,
          samples = VK_SAMPLE_COUNT_4_BIT, flags = 5, misc = 6,
          initial_layout = 79870768}
        initial_vram = {data = 0x0, row_length = 0, array_height = 0}
        dither_initial = {data = 0x4c2bae0, row_length = 367494964,
          array_height = 0}
#13 0x0000000015d208b0 in context_reset () at rsx/rsx_lib_vulkan.cpp:82
        num_images = 3
        mask = 7
#14 0x0000000000449129 in drivers_init (flags=255) at driver.c:355
        hwr = 0xa94100 <hw_render>
        video_is_threaded = false
#15 0x00000000004052b6 in retroarch_main_init (argc=6, argv=0x4c2bea0)
    at retroarch.c:1275
        init_failed = false
#16 0x000000000041a228 in content_load (info=0x4c2d2b0)
    at tasks/task_content.c:276
        i = 0
        retval = true
        rarch_argc = 6
        rarch_argv = {0x7577d60 "retroarch", 0x7576d70 "-c",
          0x7f18820 "C:\\Users\\r5\\Documents\\RA\\retroarch.cfg",
          0x7f18880 "-L",
          0x7f188c0 "C:\\Users\\r5\\Documents\\RA\\cores\\mednafen_psx_hw_libretro.dll",
          0x11657920 "C:\\Users\\r5\\Documents\\ROMs\\psx\\Tekken 3 (USA).cue", 0x0 <repeats 26 times>}
        argv_copy = {0x7577d60 "retroarch",
          0x11657920 "C:\\Users\\r5\\Documents\\ROMs\\psx\\Tekken 3 (USA).cue", 0x7576d70 "-c",
          0x7f18820 "C:\\Users\\r5\\Documents\\RA\\retroarch.cfg",
          0x7f18880 "-L",
          0x7f188c0 "C:\\Users\\r5\\Documents\\RA\\cores\\mednafen_psx_hw_libretro.dll", 0x0 <repeats 26 times>}
        rarch_argv_ptr = 0x4c2bea0
        rarch_argc_ptr = 0x4c2bfac
        wrap_args = 0x116578b0
#17 0x000000000041b4df in task_load_content (content_info=0x4c2d2b0,
    content_ctx=0x4c2d310, launched_from_menu=false, launched_from_cli=false,
    error_string=0x4c2d308) at tasks/task_content.c:821
        name = "\000\000\b\000\000\000\000\000P▒▒\004\000\000\000\000\000▒▒\n", '\000' <repeats 12 times>, "\b", '\000' <repeats 15 times>, "\001\000\000\000\000\000\000\000\020▒▒\n\000\000\000\000▒▒▒\004\000\000\000\000\004\000\000\000▒\177\000\000▒▒▒\n\000\000\000\000j\000\000\000\000\000\000\000P▒▒\004\000\000\000\000\000\000▒\004\000\000\000\000\nڮs▒▒\000\000▒▒▒\n", '\000' <repeats 20 times>, "\b\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000▒▒▒\004\000\000\000\000cOo", '\000' <repeats 13 times>, "\020ye\021\000\000\000\000\b", '\000' <repeats 17 times>...
        msg = '\000' <repeats 80 times>, "TEKKEN~1.CUE", '\000' <repeats 12 times>, "▒▒▒\n\000\000\000\000\b", '\000' <repeats 17 times>, "\b\000\000\000\000\000▒\021▒\f▒\177\000\000#", '\000' <repeats 15 times>, "\060", '\000' <repeats 15 times>, "\003\000\000\000\000\000\000\000`\000\000@\000\000\000\000\000\000H\005\000\000\000\000"...
        contentless = false
        is_inited = false
#18 0x000000000041b8cd in command_event_cmd_exec (
    data=0x1175ccc0 "C:\\Users\\r5\\Documents\\ROMs\\psx\\Tekken 3 (USA).cue", content_ctx=0x4c2d310, launched_from_cli=false, error_string=0x4c2d308)
    at tasks/task_content.c:944
        content_info = {argc = 0, argv = 0x0, args = 0x0,
          environ_get = 0x41b2f3 <menu_content_environment_get>}
#19 0x000000000041bf46 in task_push_load_content_from_playlist_from_menu (
    core_path=0x4c2e440 "C:\\Users\\r5\\Documents\\RA\\cores\\mednafen_psx_hw_libretro.dll",
    fullpath=0x1175ccc0 "C:\\Users\\r5\\Documents\\ROMs\\psx\\Tekken 3 (USA).cue", content_info=0x4c2e420, cb=0x0, user_data=0x0)
    at tasks/task_content.c:1147
        content_ctx = {subsystem = {data = 0x0, size = 0}, name_ips = 0x0,
          name_bps = 0x0, name_ups = 0x0, valid_extensions = 0x0,
          directory_cache = 0x0,
          directory_system = 0x75776a0 "C:\\Users\\r5\\Documents\\RA\\system", is_ips_pref = false, is_bps_pref = false, is_ups_pref = false,
          history_list_enable = true, block_extract = false,
          need_fullpath = false, set_supports_no_game_enable = false,
          patch_is_blocked = false, bios_is_missing = false,
          check_firmware_before_loading = false,
          temporary_content = 0x11657920}
        ret = true
        error_string = 0x0
        global = 0xa611a0 <g_extern>
        settings = 0x750bad0
        sys_info = 0xa602e0 <runloop_system>
#20 0x0000000000518505 in action_ok_playlist_entry_collection (
    path=0x1175ccc0 "C:\\Users\\r5\\Documents\\ROMs\\psx\\Tekken 3 (USA).cue", label=0x4c2f68f "collection", type=7, idx=0, entry_idx=0)
    at menu/cbs/menu_cbs_ok.c:1503
        playlist_info = {data = 0x1175cbc0, idx = 0}
        new_core_path = "C:\\Users\\r5\\Documents\\RA\\cores\\mednafen_psx_hw_libretro.dll", '\000' <repeats 34 times>, "T\002\000\000\000\000\000\000x▒▒\n\000\000\000\000x\002\000\000\000\000\000\000!▒▒▒\177\000\000\000\000\000\000\000\000\000\000-\000\000\000\000\000\000\000\070▒▒\n", '\000' <repeats 12 times>, "▒▒▒\v\000\000\000\000*\025\001▒▒\177\000\000`▒▒\n\000\000\000\000x▒▒\n\000\000\000\000x▒▒\n\000\000\000\000"...
        content_info = {argc = 0, argv = 0x0, args = 0x0, environ_get = 0x0}
        selection_ptr = 0
        playlist_initialized = false
        playlist = 0x1175cbc0
        entry_path = 0x1175ccc0 "C:\\Users\\r5\\Documents\\ROMs\\psx\\Tekken 3 (USA).cue"
        entry_label = 0x0
        core_path = 0x1175cd30 "C:\\Users\\r5\\Documents\\RA\\cores\\mednafen_psx_hw_libretro.dll"
        core_name = 0x1175cda0 "Beetle PSX HW"
        tmp_playlist = 0x1175cbc0
        menu = 0x75b1fd0
        info = 0xa602e0 <runloop_system>
        system = 0xa602e0 <runloop_system>
#21 0x0000000000513dfc in menu_entry_action (entry=0x4c2f590, i=0,
    action=MENU_ACTION_OK) at menu/widgets/menu_entry.c:518
        ret = 0
        selection_buf = 0x75af080
        cbs = 0x11657750
#22 0x00000000005507e1 in generic_menu_iterate (data=0x75b1fd0,
    userdata=0x7ed3fd0, action=MENU_ACTION_OK)
    at menu/drivers/menu_generic.c:230
        entry = {
          path = "Run", '\000' <repeats 21 times>, "\210▒3\001\000\000\000\000\t", '\000' <repeats 23 times>, "\030▒▒\n\000\000\000\000\002\000\000\000\000\000\000\000▒▒3\001\000\000\000\000\020▒▒\004\000\000\000\000▒\200h\000\000\000\000\000 \201\063\001\000\000\000\000\001\000\000\000\000\000\000\000X▒▒\004\000\000\000\000▒▒\000\000\000\000\000▒▒▒\004\000\000\000\000\004▒X\000\000\000\000\000▒▒S\a\000\000\000\000\020▒▒\004\000\000\000\000\020▒▒\004\000\000\000\000\210B▒\n\000\000\000\000▒͚;\000\000\000\000\000\001\000\000▒\177\000\000\000\200\000\000\000\000\000\000\000"...,
          label = "collection\000.\f▒\177\000\000▒\033\v\000\000\000\000\000\r\000\000\000\000\000\000\000\r\000\000\000\000\000\000\000▒▒▒▒▒\177\000\000\033\006▒▒\000\000\000\000▒\002\000\000\000\000\000\000\bݹ\r\000\000\000\000\230\230▒\n\000\000\000\000\001\000\000\000\004\000\000\000\004\000\000\000▒\177\000\000▒K2\v", '\000' <repeats 12 times>, "\r", '\000' <repeats 15 times>, "\004", '\000' <repeats 39 times>, "\001\000\000\000\000\000\000\000\070▒S\a\000\000\000\000\001\000\000\000\000\000\000\000▒▒▒\004\000\000\000\000"...,
          sublabel = "Start the content.", '\000' <repeats 16 times>, "\001", '\000' <repeats 31 times>, "X▒\r", '\000' <repeats 12 times>, "x▒▒\004\000\000\000\000\000\020\066\f▒\177\000\000▒8H\005\002\000\000\000\001\000\000\000▒\002\000\000▒\003\000\000\000\000\000\000▒▒S\a\000\000\000\000▒▒S\a\000\000\000\000\001\000\000\000\000\000\000\000▒▒S\a\000\000\000\000▒B▒\000\000\000\000\000\000▒▒\v\000\000\000\000 ▒▒\000\004\000\000\000▒8H\005\000\000\000\000\001\000\000\000\034\000\000\000▒▒▒\004\000\000\000\000"...,
          rich_label = "\177\000\000▒B▒\000\000\000\000\000\020▒▒\004", '\000' <repeats 12 times>, "\r\000\000\000\000\000\000\000\020▒W\a", '\000' <repeats 28 times>, "\001\000\000\000\000\000\000\000ܿV\000\000\000\000\000▒8H\005\000\000\000\000@▒▒\004\000\000\000\000▒▒H\005", '\000' <repeats 28 times>, "\r\000\000\000\000\001", '\000' <repeats 18 times>, "▒▒▒▒\000\000\000\000▒▒▒\004\000\000\000\000\062\"V\000\000\000\000\000\004\000\000\000\000\000\000\000▒▒▒▒\000\000\000\000/\001\000\000\002"...,
          value = "\000\000\000\000▒▒}\000\000\000\000\000\000\000\000\000\b\000\000\000\004\000\000\000\000\000\000\000@▒?\001\000\000\000\000\030\000\000\000\000\000\000\000\070:n\000\000\000\000\000\004\000\000\000\000\000\000\000@▒7\001\000\000\000\000\000\000\000?\000\000\000\000▒▒U\000\000\000\000\000\001\000\000\000\000\000\000\000▒▒?\001\000\000\000\000\000▒=\000\000\000\000\000▒▒▒\004\000\000\000\000\220▒▒\004\000\000\000\000%/V\000\000\000\000\000\020▒W\a\000\000\000\000\000\000\000\000\020\000\000\000@▒?\001\000\000\000\000\004\000\000\000\000\000\000\000\030\000\000\000▒\001\000\000▒8H\005\000\000\000\000\004\000\000\000\000\000\000\000@▒7\001\000\000\000\000\000\000\000?"...,
          entry_idx = 0, enum_idx = MENU_ENUM_LABEL_RUN, idx = 0, type = 7,
          spacing = 0}
        iterate_type = ITERATE_TYPE_DEFAULT
        file_type = 0
        ret = 0
        hash = 898266260
        enum_idx = MSG_UNKNOWN
        label = 0x7f17450 "deferred_rpl_entry_actions"
        menu = 0x75b1fd0
        selection = 0
#23 0x00000000004f8a55 in menu_driver_iterate (iterate=0x4c2fbf0)
    at menu/menu_driver.c:1568
No locals.
#24 0x0000000000407274 in runloop_check_state (settings=0x750bad0,
    input_nonblock_state=false, sleep_ms=0x4c2fdd0) at retroarch.c:2494
        trigger_input = 1
        action = MENU_ACTION_OK
        focused = true
        old_input = 0
        iter = {action = MENU_ACTION_OK, pointer = {x = 0, y = 0,
            touch = true}, mouse = {x = 0, y = 0, buttons = {left = false,
              right = false}, wheel = {up = 176, down = 56}}}
        last_input = 1
        old_fs_toggle_pressed = false
        old_focus = true
        is_focused = true
        is_alive = true
        frame_count = 177
        focused = true
        pause_nonactive = false
        fs_toggle_triggered = false
        menu_driver_binding_state = false
        menu_is_alive = true
        current_input = 1
#25 0x0000000000408155 in runloop_iterate (sleep_ms=0x4c2fdd0)
    at retroarch.c:3001
        i = 16
        input_nonblock_state = false
        settings = 0x750bad0
        max_users = 5
#26 0x000000000040175c in rarch_main (argc=1, argv=0x548c0c0, data=0x0)
    at frontend/frontend.c:131
        sleep_ms = 0
        ret = 1
        args = 0x0
#27 0x00000000004017bc in SDL_main (argc=1, argv=0x548c0c0)
    at frontend/frontend.c:151
No locals.
#28 0x00000000006f2e38 in main_getcmdline ()
No symbol table info available.
#29 0x00000000004013f8 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
        lock_free = <optimized out>
        fiberid = <optimized out>
        nested = <optimized out>
        lpszCommandLine = <optimized out>
        StartupInfo = {cb = 104, lpReserved = 0x9e7a0 "",
          lpDesktop = 0x97dc0 "Winsta0\\Default",
          lpTitle = 0x9fe50 "C:\\Users\\r5\\Documents\\RA\\retroarch_debug.exe", dwX = 0, dwY = 0, dwXSize = 0, dwYSize = 0, dwXCountChars = 0,
          dwYCountChars = 0, dwFillAttribute = 0, dwFlags = 0,
          wShowWindow = 0, cbReserved2 = 0, lpReserved2 = 0x0,
          hStdInput = 0xffffffffffffffff, hStdOutput = 0xffffffffffffffff,
          hStdError = 0xffffffffffffffff}
        inDoubleQuote = <optimized out>
#30 0x00000000004014eb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184
        ret = 255

```

**Comment by saftle** [comment]
@rz5 ah thanks for reproducing it.

@bparker06 thanks will definitely do that, just so I can provide more next time and isolate a bug potentially to a specific commit.

**Comment by rz5** [comment]
@saftle - Hi, please try reproducing this bug again. Toggling widescreen no longer causes a crash for me and I tested it on a GTX 970 and a R5 M330.

**Comment by saftle** [comment]
Coincidentally toggled widescreen on and off yesterday without remembering that I had opened an issue for it. It works great. Thank you! This can be closed.
