### ISSUE TITLE
Attempting to load an Audio CD in Beetle PSX causes an instant crash

### ISSUE THREAD

**Issue by ajshell1** [libretro/beetle-psx-libretro#227]
Description:

Whenever an Audio CD in bin/cue format is loaded by the Beetle PSX or PSX HW core, RetroArch instantly crashes.

Expected Behavior:

I expected the core to go the PSX bios screen. Beetle PCE Fast goes to it's bios screen (i.e. the "Play the audio CD". Likewise, standalone Mednafen loads the same bin/cue just fine.

For reference, the audio CD I am using is the self-titled debut album of "The Cars", made using ImgBurn.

Actual behavior: It attempts to load, and then [this message is displayed.](http://i.imgur.com/2aMXKAj.png)

As for the output log, [this is what I get] after entering "retroarch --menu --verbose >> log.txt 2>&1"

How to reproduce:

1. Get an bin/cue rip of an audio CD.

2. Try to load it with Mednafen PSX HW or regular PSX.

3. Watch it crash.

I've also found that loading .m3u files with Audio CD cues listed will also cause an instant crash.

I can't tell you when this started happening. I remember being able to use Audio CDs with Vib Ribbon a few months ago.

Version: Latest version of RetroArch, using 8/30/2017 nightly installer. Latest version of the PSX HW core was used as well.

OS: Windows 10

**Comment by TheOligopolist** [comment]
Tested this myself and can confirm this behaviour.
Running a game and then using the Disk Image Append function in the menu and selecting an audio CD image .cue will also cause the same crash.

**Comment by ajshell1** [comment]
I've also noticed that attempting to load homebrew games also causes a similar issue.

In addition, loading a PSX game and then immediately pressing the "Cycle Tray" hotkey causes the PSX to go to the bios. However, the controls don't work once in the bios. So i'm guessing that there is some kind of underlying bios issue.

**Comment by TheOligopolist** [comment]
Navigating the bios menu doesn't work with analogue enabled. This is true to how the real hardware behaves and is expected behaviour.

**Comment by ajshell1** [comment]
Whoops. You're right. sorry about that.

**Comment by rz5** [comment]
@ajshell1, you never actually linked the log output. Could you put something up please.

**Comment by ajshell1** [comment]
@rz5 Sorry about that.

[https://pastebin.com/BWDQ6UnC](https://pastebin.com/BWDQ6UnC)

**Comment by ajshell1** [comment]
I would also like to state that Standalone Mednafen PSX does not have this problem.

**Comment by ajshell1** [comment]
Update: I'm currently attempting to bisect this bug. I've found that [this](https://github.com/libretro/beetle-psx-libretro/commit/4e6edb64a2538666e162d1a31f01e495da3e5e9c) is the first build that I've tested that works. So the problem appears sometime between August 5 2015 and December 24 2014. I'll do further testing.

**Comment by ajshell1** [comment]
Bisection Complete.

This is the last version that doesn't have the bug: https://github.com/libretro/beetle-psx-libretro/commit/95d7ed845db0d718d8a7ceda640cb8bc2a81eece

The next nine commits won't compile for me on Windows.

The first one that compiles and has the bug is this one: https://github.com/libretro/beetle-psx-libretro/commit/aa92168042efaf98b46b3c47679a572bfb15b2de

**Comment by ajshell1** [comment]
To help anyone who wants to fix this, I "git cloned" all 28 commits made on July 28 2015 (i.e. the day the bug first appeared. I put them in a zip file, and you can download this file [here](https://drive.google.com/open?id=0Bz5_MQ70-bq0ekhUU0tUMGJhdjg).

Names like "beetle-psx-libretro-3da0bba3d58994d1d46b13e3f4f87dadde3a884d.zip" aren't human readable, so I put them in folders ordered chronologically.

Folders labeled "G" correctly play Audio CDs. Folders labeled "DNC" are versions that "did not compile" for me. Folders labeled "BUG" contain versions of this core that compile but have the Audio CD bug.

The 8th commit (Convert l-ec.c to C) is the last one that compiles and doesn't have the bug.

The 18th commit (Forgot to add recover-raw.h) is the first one that compiles and has the bug.

**Comment by simias** [comment]
This looks relatively simple to figure out since the code throws an exception where it "dies". Maybe beetle should try to catch these and display the contents before letting them bubble up through the C interface and abort the process? A big `try{} catch()` should do the trick.

Anyway, I suspect that the problem might come from [CalcDiscSCEx](https://github.com/libretro/beetle-psx-libretro/blob/53c6d55a0507334409d02b8e0a346099d953c1bb/libretro.cpp#L1261) or maybe even the submethod [CalcDiscSCEx_BySYSTEMCNF](https://github.com/libretro/beetle-psx-libretro/blob/53c6d55a0507334409d02b8e0a346099d953c1bb/libretro.cpp#L1128). Unfortunately I don't have an audio CD bin/cue available to test my theory (if somebody knows where to find a public domain audio bin/cue out there, I'm interested).

If you feel like poking around the code I think the lone `fp->read(pvd, 2048);` is suspicious, I expect that this will fail for audio tracks: https://github.com/libretro/beetle-psx-libretro/blob/53c6d55a0507334409d02b8e0a346099d953c1bb/libretro.cpp#L1148

I'd try replacing this with:

```c++
      try {
         fp->read(pvd, 2048);
      } catch (...) {
         ret = NULL;
         goto Breakout;
      }
```

Is calling goto from exception handlers kosher? Honestly I'm not sure if I even want to know...

The reason I suspect this is that the [`read()` method](https://github.com/libretro/beetle-psx-libretro/blob/53c6d55a0507334409d02b8e0a346099d953c1bb/mednafen/cdrom/cdromif.cpp#L730) throws if the call to `cdintf->ReadSector()` returns `false`.

[CDIF::ReadSector](https://github.com/libretro/beetle-psx-libretro/blob/53c6d55a0507334409d02b8e0a346099d953c1bb/mednafen/cdrom/cdromif.cpp#L520-L564) returns `false` if `ValidateRawSector()` returns `false`. And in turn [ValidateRawSector](https://github.com/libretro/beetle-psx-libretro/blob/53c6d55a0507334409d02b8e0a346099d953c1bb/mednafen/cdrom/cdromif.cpp#L428-L439) will always return `false` for audio sectors:

https://github.com/libretro/beetle-psx-libretro/blob/53c6d55a0507334409d02b8e0a346099d953c1bb/mednafen/cdrom/cdromif.cpp#L428-L439

**Comment by retro-wertz** [comment]
@ajshell1  im not sure if you already have done this, but can you post the contents of the .cue sheet thats having the issue?

from what i remember with mednafen cdrom stuff, depending on which cdrom code is used, audio files in .wav does not play if in cue sheet its label as AUDIO but will play when its labeled as BINARY. its its in another extension or format, it may be possible it will not run at all. not sure which cdrom code the default psx uses, but im sure the HAVE_CDROM_NEW uses the same one in pce_fast, which should support .wav in AUDIO, not entirely sure of the default one since i've always used psx images in binary formats.

imho

**Comment by ajshell1** [comment]
@retro-wertz 
Here is the .cue sheet.

`FILE "TheCars.bin" BINARY
  TRACK 01 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:00:32
  TRACK 02 AUDIO
    INDEX 01 03:45:05
  TRACK 03 AUDIO
    INDEX 01 07:28:42
  TRACK 04 AUDIO
    INDEX 01 11:11:50
  TRACK 05 AUDIO
    INDEX 00 14:41:05
    INDEX 01 14:42:50
  TRACK 06 AUDIO
    INDEX 00 17:45:30
    INDEX 01 17:46:12
  TRACK 07 AUDIO
    INDEX 01 21:59:02
  TRACK 08 AUDIO
    INDEX 01 26:11:52
  TRACK 09 AUDIO
    INDEX 01 30:53:55
`

**Comment by ajshell1** [comment]
I just tested this issue again, and it's still a problem. Is anyone interested in fixing it?

**Comment by retro-wertz** [comment]
confirmed. as pointed out by @simias those are indeed the areas where it fails to validate sector, (in my case this is where the final fail) during the "mode & 2" check

https://github.com/libretro/beetle-psx-libretro/blob/53c6d55a0507334409d02b8e0a346099d953c1bb/mednafen/cdrom/cdromif.cpp#L428-L439

. this happens when loading a pure AudioCD, but loading a mixed mode CD where in track 1 is a data track while the others tracks are audio works fine and can play the audio tracks (even able to load the cdplayer portion on the bios screen) 

https://gist.github.com/retro-wertz/1f543ecafe0d01d529af9e8987f58887

(just incase link would disappear)
```
[New Thread 0x7fffe2f3a700 (LWP 4448)]
terminate called after throwing an instance of 'MDFN_Error'

Thread 1 "retroarch_debug" received signal SIGABRT, Aborted.
0x00007ffff30f2d7f in raise () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff30f2d7f in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff30dd672 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007ffff34a958e in __gnu_cxx::__verbose_terminate_handler ()
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
        terminating = true
        t = <optimized out>
#3  0x00007ffff34afdfa in __cxxabiv1::__terminate (handler=<optimized out>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
No locals.
#4  0x00007ffff34afe57 in std::terminate ()
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
No locals.
#5  0x00007ffff34b00ac in __cxxabiv1::__cxa_throw (obj=<optimized out>, 
    tinfo=0x7fffa8490b78 <typeinfo for MDFN_Error>, dest=
    0x7fffa8387850 <MDFN_Error::~MDFN_Error()>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
        globals = <optimized out>
        header = 0x5555576124c0
#6  0x00007fffa8385aba in CDIF_Stream_Thing::read (this=0x55555698c980, 
    data=0x7fffffff8770, count=2048, error_on_eos=true)
    at mednafen/cdrom/cdromif.cpp:757
--Type <RET> for more, q to quit, c to continue without paging--
        buf = "h\r\000\000\000\000\000\000{\230\312UUU\000\000\v\000\000\000\000\000\000\000{\230\312UUU\000\000\000\000(?\000\000\212>I\235\023\363\377\177\000\000\000\000\000\000\000\000\000\000I\235\023\363\377\177\000\000\000\000\000\000\000\000\000\000I\235\023\363\377\177\000\000\000\000\000\000\000\000\000\000I\235\023\363\377\177\000\000\000\000\000\000\000\000\000\000\340\203\377\377\377\177\000\000\260\203\377\377\377\177\000\000\360\203\377\377\377\177\000\000\300\203\377\377\377\177\000\000{\000\000\000\000\000\000\000\260\252\377\377\377\177\000\000\200\230\312UUU\000\000\300U'\363\377\177\000\000\363\276\020\363\377\177\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 40 times>...
        rp = 32768
#7  0x00007fffa8394e35 in CalcDiscSCEx_BySYSTEMCNF (c=0x555557339250, 
    rr=0x7fffffff9790) at libretro.cpp:1278
        pvd = "\253\252\002?\001\000\000\000\071\216s?\274\273s? \305\377\377\377\177\000\000\000\000\200?\v\000\000\000K=aWUU\000\000\300\372TWUU\000\000VU\005?\344\070\016>\v\000\000\000/\003\000\000c\000\000\000\000\000\000\000\255\002\000\000\000\000\000;\000\000\000;\211\210\210:a\v\266:4\000\000\000\000\000\000\000\364\377\377\377H\000\000\000E\000\000\000\n\000\000\000\f\000\000\000h\357BWUU\000\000\260X\234VUU\000\000K=aWUU\000\000@\224\377\377\377\177\000\000@\254\377\377\377\177\000\000@\210\377\377\377\177\000\000@\240\377\377\377\177\000\000B\000\000\000\245O\372=\000\000\f?\245O\372=\253\252\n??\351\023>"...
        rdel = 1059947224
        rdel_len = 1060477338
        ret = 0x0
--Type <RET> for more, q to quit, c to continue without paging--
        fp = 0x55555698c980
        pvd_search_count = 1
#8 0x00007fffa8395559 in CalcDiscSCEx () at libretro.cpp:1403
```

**Comment by LibretroAdmin** [comment]
This should be resolved now
